execute pathogen#infect()
set nocompatible
syntax on
filetype plugin indent on

set ts=2 sts=2 sw=2 expandtab
set number
set history=10000
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set laststatus=2
set showmatch
set incsearch
set hlsearch
autocmd FileType ruby setlocal expandtab shiftwidth=2 tabstop=2

syntax enable
set background=dark
colorscheme solarized

" Custom ignore for ctrl-p
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'

" netrw config from https://shapeshed.com/vim-netrw/
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25

" Pane movement 
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l


execute pathogen#infect()
set nocompatible
syntax on
filetype plugin indent on

set ts=2 sts=2 sw=2 expandtab
set number
set history=10000
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set laststatus=2
set showmatch
set incsearch
set hlsearch
autocmd FileType ruby setlocal expandtab shiftwidth=2 tabstop=2
autocmd Filetype gitcommit setlocal spell textwidth=72

syntax enable
set background=dark
colorscheme solarized

" Custom ignore for ctrl-p
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'

" netrw config from https://shapeshed.com/vim-netrw/
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25

" Pane movement 
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l


