execute pathogen#infect()
set nocompatible
syntax on
filetype plugin indent on

set ts=2 sts=2 sw=2 expandtab
set number
set history=10000
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set laststatus=2
set showmatch
set incsearch
set hlsearch
autocmd FileType ruby setlocal expandtab shiftwidth=2 tabstop=2

syntax enable
set background=dark
colorscheme solarized
